import {
  Form,
  Link,
  redirect,
  useActionData,
  useLoaderData,
  useNavigation,
  useSearchParams,
} from "react-router";
import { useEffect, useMemo, useState } from "react";
import { authenticate } from "../shopify.server";
import {
  buildBrief,
  buildCreativeConcepts,
  findProduct,
  findSavedCreative,
  findSavedBrief,
  getWorkspaceSetting,
  listSavedBriefs,
  loadMerchantData,
  saveBriefRecord,
  upsertWorkspaceSetting,
} from "../models/blueprint.server";
import {
  CopyBlock,
  Icon,
  PageHeader,
  PrimaryButton,
  ProductPicker,
  SectionCard,
} from "../components/blueprint-ui";

export const loader = async ({ request }) => {
  const { admin, session } = await authenticate.admin(request);
  const url = new URL(request.url);
  const merchantData = await loadMerchantData(admin, session);
  const requestedBriefId = url.searchParams.get("briefId");
  const requestedSavedBrief = await findSavedBrief(session.shop, requestedBriefId);
  const product = requestedSavedBrief
    ? findProduct(merchantData.products, requestedSavedBrief.productId)
    : findProduct(merchantData.products, url.searchParams.get("productId"));
  const recommendationId = url.searchParams.get("recommendationId");
  const creativeId = url.searchParams.get("creativeId");
  const autoGenerate = url.searchParams.get("generate") === "1";
  const creativeContext = await resolveCreativeContext(session.shop, merchantData, creativeId);
  const autoKey = [
    "auto_brief",
    product.id,
    recommendationId || "no-rec",
    creativeId || "no-creative",
  ].join(":");
  let autoGeneratedBrief = null;

  if (autoGenerate && !requestedSavedBrief) {
    const existing = await getWorkspaceSetting(session.shop, autoKey);
    autoGeneratedBrief = await findSavedBrief(session.shop, existing?.value);

    if (!autoGeneratedBrief) {
      const context = {
        recommendationId,
        recommendationTitle: recommendationId
          ? `Recommendation ${recommendationId.replace(/^rec-/, "")}`
          : null,
        creativeId,
        ...creativeContext.context,
      };
      const generated = buildBrief(product, context);
      autoGeneratedBrief = await saveBriefRecord(session.shop, product, generated);
      await upsertWorkspaceSetting(session.shop, autoKey, autoGeneratedBrief.id);
    }
  }

  const savedBriefs = await listSavedBriefs(session.shop);
  const fallbackBrief = buildBrief(product, {
    recommendationId,
    creativeId,
    ...creativeContext.context,
  });
  const selectedSavedBrief =
    requestedSavedBrief ||
    autoGeneratedBrief ||
    savedBriefs.find((item) => item.productId === product.id);

  return {
    merchantData,
    selectedProductId: product.id,
    currentProduct: product,
    brief: selectedSavedBrief?.payload || fallbackBrief,
    selectedBriefId: selectedSavedBrief?.id || null,
    contextWarning: requestedBriefId && !requestedSavedBrief
      ? "That saved brief could not be found for this shop, so the latest product context is shown."
      : creativeId && creativeContext.warning
        ? creativeContext.warning
        : "",
    creativeContext: creativeContext.context,
    briefs: savedBriefs.length
      ? savedBriefs.map((item) => ({
          id: item.id,
          productId: item.productId,
          productTitle: item.productTitle,
          createdAt: item.createdAt,
          angle: item.angle,
          ...item.payload,
        }))
      : merchantData.products.slice(0, 5).map((item) => ({
      id: item.id,
      productId: item.id,
      createdAt: item.updatedAt || new Date().toISOString(),
      angle: buildBrief(item).hooks[0].includes("problem") ? "Problem-solution demo" : "UGC demo",
      ...buildBrief(item),
    })),
    savedCount: savedBriefs.length,
    autoGenerated: Boolean(autoGeneratedBrief),
    autoGeneratedBriefId: autoGeneratedBrief?.id || null,
  };
};

export const action = async ({ request }) => {
  const { admin, session } = await authenticate.admin(request);
  const formData = await request.formData();
  const merchantData = await loadMerchantData(admin, session);
  const product = findProduct(merchantData.products, formData.get("productId"));
  const creativeContext = await resolveCreativeContext(
    session.shop,
    merchantData,
    String(formData.get("creativeId") || ""),
  );
  const brief = buildBrief(product, {
    recommendationId: String(formData.get("recommendationId") || ""),
    creativeId: String(formData.get("creativeId") || ""),
    recommendationTitle: String(formData.get("recommendationTitle") || ""),
    creativeTitle: String(formData.get("creativeTitle") || ""),
    ...creativeContext.context,
  });
  const savedBrief = await saveBriefRecord(session.shop, product, brief);

  throw redirect(
    `/app/ad-briefs?productId=${encodeURIComponent(product.id)}&briefId=${encodeURIComponent(savedBrief.id)}&saved=1`,
  );
};

export default function AdBriefs() {
  const {
    merchantData,
    currentProduct: loaderProduct,
    brief: loaderBrief,
    briefs: loaderBriefs,
    autoGenerated,
    selectedBriefId,
    contextWarning,
    creativeContext,
  } = useLoaderData();
  const actionData = useActionData();
  const navigation = useNavigation();
  const [searchParams] = useSearchParams();
  const brief = actionData?.brief || loaderBrief;
  const currentProduct = actionData?.currentProduct || loaderProduct;
  const briefs = actionData?.briefs || loaderBriefs;
  const justSaved = Boolean(actionData?.savedBriefId || searchParams.get("saved"));
  const [copyStatus, setCopyStatus] = useState("");
  const [copyTone, setCopyTone] = useState("");
  const contextFields = useMemo(
    () => ({
      recommendationId: searchParams.get("recommendationId") || brief.context?.recommendationId || "",
      creativeId: searchParams.get("creativeId") || brief.context?.creativeId || "",
      recommendationTitle: brief.context?.recommendationTitle || "",
      creativeTitle: brief.context?.creativeTitle || "",
    }),
    [brief, searchParams],
  );

  useEffect(() => {
    if (!copyStatus) return undefined;
    const timeout = window.setTimeout(() => {
      setCopyStatus("");
      setCopyTone("");
    }, 2200);
    return () => window.clearTimeout(timeout);
  }, [copyStatus]);

  async function copyFullBrief() {
    const text = JSON.stringify(brief, null, 2);

    try {
      if (!navigator.clipboard?.writeText) throw new Error("Clipboard unavailable");
      await navigator.clipboard.writeText(text);
      setCopyStatus("Copied");
      setCopyTone("success");
    } catch {
      setCopyStatus("Copy failed");
      setCopyTone("error");
    }
  }

  return (
    <div className="bp-page bp-briefs-page">
      <PageHeader
        eyebrow="Ad Briefs"
        title="Generate an ad brief"
        subtitle="Choose a product, generate a brief, then copy the parts you need."
        action={
          <PrimaryButton as="button" type="submit" form="bp-brief-form">
            <Icon name="sparkles" /> Generate brief
          </PrimaryButton>
        }
      />

      <div className="bp-section-stack">
        <SectionCard
          heading="1. Choose product"
          description="Product data provides the context for hooks, script, and CTA options."
          icon="sparkles"
          className="bp-form-panel"
        >
          <Form method="post" className="bp-form-grid bp-brief-selector" id="bp-brief-form">
            <ProductPicker
              products={merchantData.products}
              selectedProductId={currentProduct.id}
            />
            <input type="hidden" name="recommendationId" value={contextFields.recommendationId} />
            <input type="hidden" name="creativeId" value={contextFields.creativeId} />
            <input type="hidden" name="recommendationTitle" value={contextFields.recommendationTitle} />
            <input type="hidden" name="creativeTitle" value={contextFields.creativeTitle} />
            {navigation.state === "submitting" && <span className="bp-submit-state">Generating...</span>}
            {justSaved && <span className="bp-submit-state">Saved to brief history</span>}
            {autoGenerated && <span className="bp-submit-state">Generated from recommendation context</span>}
            {copyStatus && <span className="bp-submit-state">{copyStatus}</span>}
          </Form>
        </SectionCard>

        {contextWarning && (
          <div className="bp-insight-card">
            <Icon name="warning" />
            <p>{contextWarning}</p>
          </div>
        )}

        {(selectedBriefId || creativeContext?.creativeTitle) && (
          <div className="bp-brief-context-card">
            <Icon name={creativeContext?.creativeTitle ? "video" : "brief"} />
            <div>
              <span>{selectedBriefId ? "Active saved brief" : "Creative source"}</span>
              <strong>
                {selectedBriefId
                  ? `${brief.angle || "Saved brief"} · ${brief.productTitle}`
                  : creativeContext.creativeTitle}
              </strong>
              {creativeContext?.creativeAnalysis && <p>{creativeContext.creativeAnalysis}</p>}
            </div>
          </div>
        )}

        <div className="bp-brief-layout">
          <aside className="bp-brief-list">
            <p className="bp-brief-list-label">History</p>
            {briefs.map((item) => (
              <Link
                className={item.id === selectedBriefId ? "bp-brief-list-item bp-brief-list-item-active" : "bp-brief-list-item"}
                key={item.id}
                to={`/app/ad-briefs?productId=${encodeURIComponent(item.productId || "")}&briefId=${encodeURIComponent(item.id || "")}`}
              >
                <span className="bp-brief-list-item-top">
                  <span>{item.angle || "Creative brief"}</span>
                  <small>{new Date(item.createdAt).toLocaleDateString()}</small>
                </span>
                <strong>{item.productTitle}</strong>
                <em>
                  View brief
                  <Icon name="brief" />
                </em>
              </Link>
            ))}
          </aside>

          <article className="bp-brief-document">
            <header className="bp-brief-document-header">
              <div className="bp-brief-title">
                <Icon name="brief" />
                <div>
                  <span>{brief.hooks[0]?.includes("problem") ? "Problem-solution demo" : "Creative brief"}</span>
                  <h2>{brief.productTitle}</h2>
                  <p>
                    Brief · {brief.generatedAt ? new Date(brief.generatedAt).toLocaleString() : new Date().toLocaleString()}
                  </p>
                </div>
              </div>
              <button
                type="button"
                className={`bp-copy-button ${copyTone ? `bp-copy-button-${copyTone}` : ""}`}
                onClick={copyFullBrief}
              >
                {copyStatus ? copyStatus : "Copy full brief"}
              </button>
            </header>

            <div className="bp-brief-document-body">
              <section>
                <h3><Icon name="activity" /> Hooks</h3>
                <div className="bp-brief-grid bp-brief-grid-3">
                  {brief.hooks.map((hook, index) => (
                    <CopyBlock label={`Hook ${index + 1}`} text={hook} key={hook} />
                  ))}
                </div>
              </section>

              <details className="bp-brief-details" open>
                <summary>Production details</summary>
                <section>
                  <h3><Icon name="list" /> Captions</h3>
                  <div className="bp-brief-grid">
                    {brief.captions.map((caption) => (
                      <CopyBlock label="Caption" text={caption} key={caption} />
                    ))}
                  </div>
                </section>

                <section>
                  <h3><Icon name="video" /> Script structure</h3>
                  <ol className="bp-script-list">
                    {brief.script.map((line) => (
                      <li key={line}>{line}</li>
                    ))}
                  </ol>
                </section>

                <section>
                  <h3><Icon name="sparkles" /> Visual concept</h3>
                  <div className="bp-visual-card">
                    {brief.visualConcepts[0]}
                  </div>
                </section>

                <section>
                  <h3><Icon name="check" /> CTA options</h3>
                  <div className="bp-brief-grid bp-brief-grid-3">
                    {brief.ctas.map((cta) => (
                      <CopyBlock label="CTA" text={cta} key={cta} />
                    ))}
                  </div>
                </section>

                <section>
                  <div className="bp-insight-card">
                    <Icon name="sparkles" />
                    <p>{brief.creatorDirection}</p>
                  </div>
                </section>
              </details>
            </div>
          </article>
        </div>
      </div>
    </div>
  );
}

async function resolveCreativeContext(shop, merchantData, creativeId) {
  if (!creativeId) return { context: {}, warning: "" };

  const savedCreative = await findSavedCreative(shop, creativeId);

  if (savedCreative) {
    const payload = savedCreative.payload || {};
    const analysis = payload.analysis || {};

    return {
      context: {
        creativeId,
        creativeTitle: savedCreative.title,
        creativeScore: [
          analysis.hookScore && `Hook ${analysis.hookScore * 10}/100`,
          analysis.clarityScore && `Clarity ${analysis.clarityScore * 10}/100`,
          analysis.ctaScore && `CTA ${analysis.ctaScore * 10}/100`,
        ].filter(Boolean).join(", "),
        creativePlatform: savedCreative.sourceType,
        creativeAnalysis: analysis.pacingNotes || analysis.firstTenSecondRisk || payload.brief || "",
        creativeRecommendation: analysis.rewriteSuggestions?.[0] || "",
        hook: analysis.rewriteSuggestions?.[0] || payload.brief || "",
        cta: analysis.ctaScore >= 7 ? "Keep the CTA direct and visible" : "Add a direct shop CTA",
        angle: savedCreative.angle || payload.brief || "Creative-derived brief",
      },
      warning: "",
    };
  }

  const concepts = buildCreativeConcepts(merchantData.products);
  const concept = concepts.find((item) => item.productId === creativeId);

  if (concept) {
    return {
      context: {
        creativeId,
        creativeTitle: `${concept.productTitle} · ${concept.angle}`,
        creativeAnalysis: concept.risk,
        creativeRecommendation: concept.visual,
        hook: concept.hook,
        cta: concept.cta,
        angle: concept.angle,
        visual: concept.visual,
      },
      warning: "",
    };
  }

  return {
    context: { creativeId },
    warning: "That creative could not be found, so the brief is using product context only.",
  };
}
